import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";
import { LogoOutlineBg } from "./components/LogoOutlineBg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zap by Paycrest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Providers>
        <body
          className={`bg-white transition-colors dark:bg-neutral-900 ${inter.className}`}
        >
          <Navbar />
          <div className="max-w-mobile mx-auto flex min-h-screen flex-col items-center px-4 pt-20 transition-all">
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
          <LogoOutlineBg />
        </body>
      </Providers>
    </html>
  );
}
